/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    doctors: Doctor;
    'medical-staff': MedicalStaff;
    vaccines: Vaccine;
    certificates: Certificate;
    articles: Article;
    'page-views': PageView;
    'alur-pengaduan-steps': AlurPengaduanStep;
    pengaduan: Pengaduan;
    'kritik-saran': KritikSaran;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    'medical-staff': MedicalStaffSelect<false> | MedicalStaffSelect<true>;
    vaccines: VaccinesSelect<false> | VaccinesSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    'alur-pengaduan-steps': AlurPengaduanStepsSelect<false> | AlurPengaduanStepsSelect<true>;
    pengaduan: PengaduanSelect<false> | PengaduanSelect<true>;
    'kritik-saran': KritikSaranSelect<false> | KritikSaranSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'operational-hours': OperationalHour;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'operational-hours': OperationalHoursSelect<false> | OperationalHoursSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Superadmin: akses penuh. Admin: hanya kelola artikel.
   */
  role: 'superadmin' | 'admin';
  /**
   * Cara akun ini boleh masuk ke dashboard. Pilih "Akun Google" bila pengguna tidak diberi kata sandi.
   */
  metodeLogin: 'sandi' | 'google' | 'keduanya';
  /**
   * Penanda tetap akun Google, terisi otomatis saat pengguna pertama kali masuk lewat Google.
   */
  googleSub?: string | null;
  /**
   * Nama unit/lokasi layanan (untuk akun Admin). Kosongkan untuk Superadmin.
   */
  lokasi?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Keterangan gambar untuk pembaca layar (aksesibilitas).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  nama: string;
  spesialisasi: string;
  foto?: (number | null) | Media;
  /**
   * mis. Senin–Jumat, 08.00–11.00
   */
  jadwalPraktik?: string | null;
  aktif?: boolean | null;
  /**
   * Poli/unit layanan terkait.
   */
  poli?:
    | (
        | 'umum'
        | 'gigi'
        | 'kia-kb'
        | 'lansia'
        | 'gizi'
        | 'sanitasi'
        | 'mtbs'
        | 'lab'
        | 'farmasi'
        | 'iva'
        | 'promkes'
        | 'ugd'
        | 'tata-usaha'
        | 'keuangan'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-staff".
 */
export interface MedicalStaff {
  id: number;
  nama: string;
  jabatan: 'dokter' | 'perawat' | 'bidan' | 'apoteker' | 'analis' | 'gizi' | 'sanitarian' | 'administrasi' | 'lainnya';
  foto?: (number | null) | Media;
  aktif?: boolean | null;
  /**
   * Poli/unit layanan terkait.
   */
  poli?:
    | (
        | 'umum'
        | 'gigi'
        | 'kia-kb'
        | 'lansia'
        | 'gizi'
        | 'sanitasi'
        | 'mtbs'
        | 'lab'
        | 'farmasi'
        | 'iva'
        | 'promkes'
        | 'ugd'
        | 'tata-usaha'
        | 'keuangan'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vaccines".
 */
export interface Vaccine {
  id: number;
  nama: string;
  /**
   * mis. Campak, Polio, DPT-HB-Hib
   */
  jenis?: string | null;
  /**
   * Jumlah dosis tersedia.
   */
  stok: number;
  satuan?: string | null;
  keterangan?: string | null;
  /**
   * Poli/unit layanan terkait.
   */
  poli?:
    | (
        | 'umum'
        | 'gigi'
        | 'kia-kb'
        | 'lansia'
        | 'gizi'
        | 'sanitasi'
        | 'mtbs'
        | 'lab'
        | 'farmasi'
        | 'iva'
        | 'promkes'
        | 'ugd'
        | 'tata-usaha'
        | 'keuangan'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  judul: string;
  penerbit?: string | null;
  tanggal?: string | null;
  /**
   * Scan/berkas sertifikat (gambar atau PDF).
   */
  berkas: number | Media;
  keterangan?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Dikosongkan = dibuat otomatis dari judul.
   */
  slug?: string | null;
  cover?: (number | null) | Media;
  /**
   * Ringkasan singkat untuk daftar & preview.
   */
  excerpt?: string | null;
  content?: string | null;
  category?: ('berita' | 'pengumuman' | 'kegiatan' | 'kesehatan') | null;
  author?: (number | null) | User;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: number;
  path: string;
  referrer?: string | null;
  uaHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alur-pengaduan-steps".
 */
export interface AlurPengaduanStep {
  id: number;
  order: number;
  title: string;
  description: string;
  details?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pengaduan".
 */
export interface Pengaduan {
  id: number;
  name: string;
  contact: string;
  subject: string;
  message: string;
  status: 'baru' | 'diproses' | 'selesai';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kritik-saran".
 */
export interface KritikSaran {
  id: number;
  name: string;
  contact: string;
  subject: string;
  message: string;
  status: 'baru' | 'diproses' | 'selesai';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'medical-staff';
        value: number | MedicalStaff;
      } | null)
    | ({
        relationTo: 'vaccines';
        value: number | Vaccine;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'page-views';
        value: number | PageView;
      } | null)
    | ({
        relationTo: 'alur-pengaduan-steps';
        value: number | AlurPengaduanStep;
      } | null)
    | ({
        relationTo: 'pengaduan';
        value: number | Pengaduan;
      } | null)
    | ({
        relationTo: 'kritik-saran';
        value: number | KritikSaran;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  metodeLogin?: T;
  googleSub?: T;
  lokasi?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  nama?: T;
  spesialisasi?: T;
  foto?: T;
  jadwalPraktik?: T;
  aktif?: T;
  poli?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-staff_select".
 */
export interface MedicalStaffSelect<T extends boolean = true> {
  nama?: T;
  jabatan?: T;
  foto?: T;
  aktif?: T;
  poli?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vaccines_select".
 */
export interface VaccinesSelect<T extends boolean = true> {
  nama?: T;
  jenis?: T;
  stok?: T;
  satuan?: T;
  keterangan?: T;
  poli?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  judul?: T;
  penerbit?: T;
  tanggal?: T;
  berkas?: T;
  keterangan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  author?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  path?: T;
  referrer?: T;
  uaHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alur-pengaduan-steps_select".
 */
export interface AlurPengaduanStepsSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  description?: T;
  details?:
    | T
    | {
        text?: T;
        id?: T;
      };
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pengaduan_select".
 */
export interface PengaduanSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kritik-saran_select".
 */
export interface KritikSaranSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-hours".
 */
export interface OperationalHour {
  id: number;
  jadwal: {
    hari: string;
    jam: string;
    id?: string | null;
  }[];
  catatan?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  namaInstansi?: string | null;
  alamat?: string | null;
  telepon?: string | null;
  email?: string | null;
  sosialMedia?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-hours_select".
 */
export interface OperationalHoursSelect<T extends boolean = true> {
  jadwal?:
    | T
    | {
        hari?: T;
        jam?: T;
        id?: T;
      };
  catatan?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  namaInstansi?: T;
  alamat?: T;
  telepon?: T;
  email?: T;
  sosialMedia?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}