/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    doctors: Doctor;
    'medical-staff': MedicalStaff;
    vaccines: Vaccine;
    certificates: Certificate;
    articles: Article;
    'page-views': PageView;
    services: Service;
    posyandu: Posyandu;
    facilities: Facility;
    complaints: Complaint;
    'org-chart': OrgChart;
    'service-statistics': ServiceStatistic;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    doctors: DoctorsSelect<false> | DoctorsSelect<true>;
    'medical-staff': MedicalStaffSelect<false> | MedicalStaffSelect<true>;
    vaccines: VaccinesSelect<false> | VaccinesSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posyandu: PosyanduSelect<false> | PosyanduSelect<true>;
    facilities: FacilitiesSelect<false> | FacilitiesSelect<true>;
    complaints: ComplaintsSelect<false> | ComplaintsSelect<true>;
    'org-chart': OrgChartSelect<false> | OrgChartSelect<true>;
    'service-statistics': ServiceStatisticsSelect<false> | ServiceStatisticsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'operational-hours': OperationalHour;
    'site-settings': SiteSetting;
    profile: Profile;
  };
  globalsSelect: {
    'operational-hours': OperationalHoursSelect<false> | OperationalHoursSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    profile: ProfileSelect<false> | ProfileSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Superadmin: akses penuh. Admin: hanya kelola artikel.
   */
  role: 'superadmin' | 'admin';
  /**
   * Cara akun ini boleh masuk ke dashboard. Pilih "Akun Google" bila pengguna tidak diberi kata sandi.
   */
  metodeLogin: 'sandi' | 'google' | 'keduanya';
  /**
   * Penanda tetap akun Google, terisi otomatis saat pengguna pertama kali masuk lewat Google.
   */
  googleSub?: string | null;
  /**
   * Nama unit/lokasi layanan (untuk akun Admin). Kosongkan untuk Superadmin.
   */
  lokasi?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Keterangan gambar untuk pembaca layar (aksesibilitas).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors".
 */
export interface Doctor {
  id: number;
  nama: string;
  spesialisasi: string;
  foto?: (number | null) | Media;
  jadwalPraktik?:
    | {
        hari: 'senin' | 'selasa' | 'rabu' | 'kamis' | 'jumat' | 'sabtu' | 'minggu';
        /**
         * Format 24 jam, mis. 08.00
         */
        jamMulai: string;
        /**
         * Format 24 jam, mis. 11.00
         */
        jamSelesai: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pendidikan terakhir, mis. S1 Kedokteran Universitas Lambung Mangkurat
   */
  pendidikan?: string | null;
  /**
   * Surat Tanda Registrasi. Kosongkan bila belum tersedia.
   */
  nomorSTR?: string | null;
  /**
   * Perkenalan singkat yang tampil di halaman profil dokter.
   */
  deskripsi?: string | null;
  aktif?: boolean | null;
  /**
   * Poli/unit layanan terkait.
   */
  poli?:
    | (
        | 'umum'
        | 'gigi'
        | 'kia-kb'
        | 'lansia'
        | 'gizi'
        | 'sanitasi'
        | 'mtbs'
        | 'lab'
        | 'farmasi'
        | 'iva'
        | 'promkes'
        | 'ugd'
        | 'tata-usaha'
        | 'keuangan'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-staff".
 */
export interface MedicalStaff {
  id: number;
  nama: string;
  jabatan: 'dokter' | 'perawat' | 'bidan' | 'apoteker' | 'analis' | 'gizi' | 'sanitarian' | 'administrasi' | 'lainnya';
  /**
   * Mis. "Perawat Ahli Madya". Inilah yang tampil di situs.
   */
  jabatanLengkap?: string | null;
  foto?: (number | null) | Media;
  aktif?: boolean | null;
  /**
   * Poli/unit layanan terkait.
   */
  poli?:
    | (
        | 'umum'
        | 'gigi'
        | 'kia-kb'
        | 'lansia'
        | 'gizi'
        | 'sanitasi'
        | 'mtbs'
        | 'lab'
        | 'farmasi'
        | 'iva'
        | 'promkes'
        | 'ugd'
        | 'tata-usaha'
        | 'keuangan'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vaccines".
 */
export interface Vaccine {
  id: number;
  nama: string;
  /**
   * mis. Campak, Polio, DPT-HB-Hib
   */
  jenis?: string | null;
  /**
   * Jumlah dosis tersedia.
   */
  stok: number;
  satuan?: string | null;
  keterangan?: string | null;
  /**
   * Poli/unit layanan terkait.
   */
  poli?:
    | (
        | 'umum'
        | 'gigi'
        | 'kia-kb'
        | 'lansia'
        | 'gizi'
        | 'sanitasi'
        | 'mtbs'
        | 'lab'
        | 'farmasi'
        | 'iva'
        | 'promkes'
        | 'ugd'
        | 'tata-usaha'
        | 'keuangan'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  judul: string;
  jenis: 'akreditasi' | 'penghargaan';
  penerbit?: string | null;
  tanggal?: string | null;
  /**
   * Scan/berkas sertifikat (gambar atau PDF).
   */
  berkas: number | Media;
  keterangan?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Dikosongkan = dibuat otomatis dari judul.
   */
  slug?: string | null;
  cover?: (number | null) | Media;
  /**
   * Ringkasan singkat untuk daftar & preview.
   */
  excerpt?: string | null;
  content?: string | null;
  category?: ('berita' | 'pengumuman' | 'kegiatan' | 'kesehatan') | null;
  author?: (number | null) | User;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: number;
  path: string;
  referrer?: string | null;
  uaHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  nama: string;
  /**
   * Dikosongkan = dibuat otomatis dari judul.
   */
  slug?: string | null;
  /**
   * Kosongkan bila ini layanan utama. Isi bila ini rincian dari layanan lain.
   */
  induk?: (number | null) | Service;
  /**
   * Mis. "Senin–Kamis 08.00–11.00", "24 jam", "Sesuai Jadwal", "Jika ada kasus".
   */
  jadwal?: string | null;
  kategori: 'dalam-gedung' | 'luar-gedung' | 'posyandu';
  /**
   * Penjelasan singkat untuk warga. Hindari istilah medis yang tidak umum.
   */
  deskripsi?: string | null;
  /**
   * Mis. "Kartu BPJS", "KTP asli". Satu baris satu syarat.
   */
  persyaratan?:
    | {
        isi: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Angka lebih kecil tampil lebih dulu. Isi 0 bila tidak ingin diatur.
   */
  urutan?: number | null;
  aktif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posyandu".
 */
export interface Posyandu {
  id: number;
  nama: string;
  alamat?: string | null;
  /**
   * Layanan yang tersedia di posyandu ini.
   */
  layanan?: (number | Service)[] | null;
  jadwal?:
    | {
        hari: 'senin' | 'selasa' | 'rabu' | 'kamis' | 'jumat' | 'sabtu' | 'minggu';
        /**
         * Mis. "Minggu ke-2 setiap bulan, 08.00–11.00"
         */
        keterangan?: string | null;
        id?: string | null;
      }[]
    | null;
  penanggungJawab?: string | null;
  /**
   * Nomor telepon kader atau penanggung jawab. Boleh dikosongkan.
   */
  kontak?: string | null;
  /**
   * Angka lebih kecil tampil lebih dulu.
   */
  urutan?: number | null;
  aktif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities".
 */
export interface Facility {
  id: number;
  nama: string;
  kategori: 'ruang' | 'kantor' | 'alat' | 'kendaraan' | 'penunjang';
  deskripsi?: string | null;
  /**
   * Banyaknya unit. Kosongkan bila tidak relevan.
   */
  jumlah?: number | null;
  foto?: (number | null) | Media;
  /**
   * Angka lebih kecil tampil lebih dulu.
   */
  urutan?: number | null;
  aktif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "complaints".
 */
export interface Complaint {
  id: number;
  /**
   * Satu kalimat pokok masalahnya.
   */
  ringkasan: string;
  isi: string;
  /**
   * Boleh dikosongkan bila pengadu ingin anonim.
   */
  nama?: string | null;
  /**
   * Nomor HP atau email, untuk menyampaikan tanggapan.
   */
  kontak?: string | null;
  kategori?: ('layanan' | 'petugas' | 'sarana' | 'saran' | 'lainnya') | null;
  persetujuanPrivasi: boolean;
  status: 'baru' | 'diproses' | 'selesai';
  tanggapan?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "org-chart".
 */
export interface OrgChart {
  id: number;
  jabatan: string;
  /**
   * Nama pejabat. Kosongkan bila posisi sedang lowong.
   */
  nama?: string | null;
  foto?: (number | null) | Media;
  /**
   * Jabatan di atasnya. Kosongkan untuk Kepala Puskesmas (puncak struktur).
   */
  atasan?: (number | null) | OrgChart;
  /**
   * Urutan di antara jabatan dengan atasan yang sama.
   */
  urutan?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-statistics".
 */
export interface ServiceStatistic {
  id: number;
  /**
   * Mis. "2025". Satu periode = satu kumpulan angka.
   */
  periode: string;
  kelompok: 'umur' | 'asuransi' | 'poli' | 'status-pulang';
  /**
   * Mis. "Balita (0-5 Tahun)", "BPJS Kesehatan".
   */
  label: string;
  jumlah: number;
  /**
   * Urutan tampil dalam kelompoknya.
   */
  urutan?: number | null;
  /**
   * Dari mana angkanya diambil, mis. "e-Puskesmas, diakses 31 Januari 2026".
   */
  sumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'doctors';
        value: number | Doctor;
      } | null)
    | ({
        relationTo: 'medical-staff';
        value: number | MedicalStaff;
      } | null)
    | ({
        relationTo: 'vaccines';
        value: number | Vaccine;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'page-views';
        value: number | PageView;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posyandu';
        value: number | Posyandu;
      } | null)
    | ({
        relationTo: 'facilities';
        value: number | Facility;
      } | null)
    | ({
        relationTo: 'complaints';
        value: number | Complaint;
      } | null)
    | ({
        relationTo: 'org-chart';
        value: number | OrgChart;
      } | null)
    | ({
        relationTo: 'service-statistics';
        value: number | ServiceStatistic;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  metodeLogin?: T;
  googleSub?: T;
  lokasi?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "doctors_select".
 */
export interface DoctorsSelect<T extends boolean = true> {
  nama?: T;
  spesialisasi?: T;
  foto?: T;
  jadwalPraktik?:
    | T
    | {
        hari?: T;
        jamMulai?: T;
        jamSelesai?: T;
        id?: T;
      };
  pendidikan?: T;
  nomorSTR?: T;
  deskripsi?: T;
  aktif?: T;
  poli?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-staff_select".
 */
export interface MedicalStaffSelect<T extends boolean = true> {
  nama?: T;
  jabatan?: T;
  jabatanLengkap?: T;
  foto?: T;
  aktif?: T;
  poli?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vaccines_select".
 */
export interface VaccinesSelect<T extends boolean = true> {
  nama?: T;
  jenis?: T;
  stok?: T;
  satuan?: T;
  keterangan?: T;
  poli?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  judul?: T;
  jenis?: T;
  penerbit?: T;
  tanggal?: T;
  berkas?: T;
  keterangan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  author?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  path?: T;
  referrer?: T;
  uaHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  nama?: T;
  slug?: T;
  induk?: T;
  jadwal?: T;
  kategori?: T;
  deskripsi?: T;
  persyaratan?:
    | T
    | {
        isi?: T;
        id?: T;
      };
  urutan?: T;
  aktif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posyandu_select".
 */
export interface PosyanduSelect<T extends boolean = true> {
  nama?: T;
  alamat?: T;
  layanan?: T;
  jadwal?:
    | T
    | {
        hari?: T;
        keterangan?: T;
        id?: T;
      };
  penanggungJawab?: T;
  kontak?: T;
  urutan?: T;
  aktif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities_select".
 */
export interface FacilitiesSelect<T extends boolean = true> {
  nama?: T;
  kategori?: T;
  deskripsi?: T;
  jumlah?: T;
  foto?: T;
  urutan?: T;
  aktif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "complaints_select".
 */
export interface ComplaintsSelect<T extends boolean = true> {
  ringkasan?: T;
  isi?: T;
  nama?: T;
  kontak?: T;
  kategori?: T;
  persetujuanPrivasi?: T;
  status?: T;
  tanggapan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "org-chart_select".
 */
export interface OrgChartSelect<T extends boolean = true> {
  jabatan?: T;
  nama?: T;
  foto?: T;
  atasan?: T;
  urutan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-statistics_select".
 */
export interface ServiceStatisticsSelect<T extends boolean = true> {
  periode?: T;
  kelompok?: T;
  label?: T;
  jumlah?: T;
  urutan?: T;
  sumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-hours".
 */
export interface OperationalHour {
  id: number;
  jadwal: {
    hari: string;
    jam: string;
    id?: string | null;
  }[];
  catatan?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  namaInstansi?: string | null;
  alamat?: string | null;
  telepon?: string | null;
  email?: string | null;
  /**
   * Nomor gawat darurat / PSC 119, tampil terpisah dari telepon utama.
   */
  teleponDarurat?: string | null;
  namaPetugasDarurat?: string | null;
  sosialMedia?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number;
  kodePuskesmas?: string | null;
  kepalaPuskesmas?: string | null;
  /**
   * Mis. Perkotaan / Pedesaan
   */
  kategori?: string | null;
  /**
   * Mis. Puskesmas Non Perawatan
   */
  jenis?: string | null;
  /**
   * Mis. Ibu Kota Kab/Kota
   */
  letak?: string | null;
  /**
   * Mis. Perbatasan
   */
  topografi?: string | null;
  /**
   * Mis. 105,760 Km²
   */
  luasWilayah?: string | null;
  /**
   * Mis. 9 (7 Desa, 2 Kelurahan)
   */
  jumlahDesa?: string | null;
  jumlahRT?: number | null;
  jumlahPenduduk?: number | null;
  jumlahKK?: number | null;
  visi?: string | null;
  /**
   * Mis. "Visi pembangunan Kabupaten Tanah Bumbu, RPJMD 2025–2029"
   */
  sumberVisi?: string | null;
  misi?:
    | {
        isi: string;
        id?: string | null;
      }[]
    | null;
  motto?: string | null;
  maklumatPelayanan?: string | null;
  budayaKerja?:
    | {
        /**
         * Mis. "5S" atau "5R"
         */
        judul: string;
        /**
         * Mis. "Pelayanan kepada masyarakat"
         */
        keterangan?: string | null;
        butir?:
          | {
              isi: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Riwayat singkat berdirinya Puskesmas. Boleh dikosongkan.
   */
  sejarah?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operational-hours_select".
 */
export interface OperationalHoursSelect<T extends boolean = true> {
  jadwal?:
    | T
    | {
        hari?: T;
        jam?: T;
        id?: T;
      };
  catatan?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  namaInstansi?: T;
  alamat?: T;
  telepon?: T;
  email?: T;
  teleponDarurat?: T;
  namaPetugasDarurat?: T;
  sosialMedia?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  kodePuskesmas?: T;
  kepalaPuskesmas?: T;
  kategori?: T;
  jenis?: T;
  letak?: T;
  topografi?: T;
  luasWilayah?: T;
  jumlahDesa?: T;
  jumlahRT?: T;
  jumlahPenduduk?: T;
  jumlahKK?: T;
  visi?: T;
  sumberVisi?: T;
  misi?:
    | T
    | {
        isi?: T;
        id?: T;
      };
  motto?: T;
  maklumatPelayanan?: T;
  budayaKerja?:
    | T
    | {
        judul?: T;
        keterangan?: T;
        butir?:
          | T
          | {
              isi?: T;
              id?: T;
            };
        id?: T;
      };
  sejarah?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}